[gcp_service_account]
type = "service_account"
project_id = "caramel-hallway-452219-i8"
private_key_id = "7d1bedf46f713952f30e0b6d0a0d84c71ada2a9f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCVmL6qt2MmRu4Z
FRix/nfa9akNpjbpJN3rR2hHPkGHcPnqP0UI83rbojRSuP5SUdegcLIH/jGpSBC4
yrPt6hmdXgqpxWeqS5ahNGW52oRMpgO/eTbJ2UAOlg2NVH0WK+1k9wMsByHgIXJr
...
6d3wkzx0AeNPrGNjRgP/NlU=
-----END PRIVATE KEY-----"""
client_email = "pdf-translate@caramel-hallway-452219-i8.iam.gserviceaccount.com"
client_id = "113926404473484080068"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/pdf-translate%40caramel-hallway-452219-i8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
